var searchData=
[
  ['common_20application_20libraries',['Common Application Libraries',['../group__app__common.html',1,'']]],
  ['common_20application_20libraries',['Common Application Libraries',['../group__app__common__serialization.html',1,'']]],
  ['common_20application_20error_20handler',['Common application error handler',['../group__app__error.html',1,'']]],
  ['cycling_20speed_20and_20cadence_20service_20feature_20bits',['Cycling Speed and Cadence Service feature bits',['../group___b_l_e___c_s_c_s___f_e_a_t_u_r_e_s.html',1,'']]],
  ['characteristic_20presentation_20formats',['Characteristic Presentation Formats',['../group___b_l_e___g_a_t_t___c_p_f___f_o_r_m_a_t_s.html',1,'']]],
  ['command_20decoder',['Command Decoder',['../group__ble__rpc__cmd__decoder.html',1,'']]],
  ['command_20encoder',['Command Encoder',['../group__ble__rpc__cmd__encoder.html',1,'']]],
  ['cycling_20speed_20and_20cadence_20application',['Cycling Speed and Cadence Application',['../group__ble__sdk__app__csc.html',1,'']]],
  ['common_20definitions_20for_20ble_20and_20gazell',['Common definitions for BLE and Gazell',['../group__ble__sdk__app__gzll__common.html',1,'']]],
  ['connection_20parameters_20negotiation',['Connection Parameters Negotiation',['../group__ble__sdk__lib__conn__params.html',1,'']]],
  ['cycling_20speed_20and_20cadence_20service',['Cycling Speed and Cadence Service',['../group__ble__sdk__srv__csc.html',1,'']]],
  ['common_20types_20and_20macro_20definitions',['Common types and macro definitions',['../group__ble__types.html',1,'']]],
  ['connecting_20to_20a_20bonded_20master',['Connecting to a bonded master',['../group___b_o_n_d_e_d___m_a_s_t_e_r.html',1,'']]],
  ['cccd_20bit_20definitions',['CCCD bit definitions',['../group___c_c_c_d___b_i_t_s.html',1,'']]],
  ['cherry8x16_20keyboard_20application',['Cherry8x16 Keyboard Application',['../group__cherry8x16__example.html',1,'']]],
  ['crc_20compute',['CRC compute',['../group__crc__compute.html',1,'']]],
  ['cherry8x16_20keyboard_20application',['Cherry8x16 Keyboard Application',['../group__foftt__cherry8x16__example.html',1,'']]],
  ['configurable_20common_20page_20data',['Configurable common page data',['../group__foftt__sdm__tx__configurable__common__page__data.html',1,'']]],
  ['common',['Common',['../group__nrf514__examples__nrf6310__common.html',1,'']]],
  ['common',['Common',['../group__nrf518__examples__nrf6310__common.html',1,'']]],
  ['common',['Common',['../group__nrf__examples__pca10000.html',1,'']]],
  ['common',['Common',['../group__nrf__examples__pca10001.html',1,'']]],
  ['common',['Common',['../group__nrf__examples__pca10003.html',1,'']]],
  ['commands_20encoder',['Commands Encoder',['../group__rpc__command__encoder.html',1,'']]],
  ['configurable_20common_20page_20data',['Configurable common page data',['../group__sdm__tx__configurable__common__page__data.html',1,'']]],
  ['connecting_20to_20an_20unbonded_20master',['Connecting to an unbonded master',['../group___u_n_b_o_n_d_e_d___m_a_s_t_e_r.html',1,'']]],
  ['characteristic_20uuid_20definitions',['Characteristic UUID definitions',['../group___u_u_i_d___c_h_a_r_a_c_t_e_r_i_s_t_i_c_s.html',1,'']]]
];
