var searchData=
[
  ['definitions_20for_20the_20alert_20level_20characteristic_20values',['Definitions for the Alert Level characteristic values',['../group___a_l_e_r_t___l_e_v_e_l___v_a_l_u_e_s.html',1,'']]],
  ['definitions',['Definitions',['../group__ant__sdm__rx__module__definitions.html',1,'']]],
  ['data_20page_202_20_2d_20status_20byte_20definitions',['Data page 2 - Status byte definitions',['../group__ant__sdm__rx__page__2__status__byte__definitions.html',1,'']]],
  ['definitions',['Definitions',['../group__ant__sdm__tx__module__definitions.html',1,'']]],
  ['defines',['Defines',['../group___b_l_e___c_o_m_m_o_n___d_e_f_i_n_e_s.html',1,'']]],
  ['defines',['Defines',['../group___b_l_e___g_a_p___d_e_f_i_n_e_s.html',1,'']]],
  ['defines',['Defines',['../group___b_l_e___g_a_t_t___d_e_f_i_n_e_s.html',1,'']]],
  ['defines',['Defines',['../group___b_l_e___g_a_t_t_c___d_e_f_i_n_e_s.html',1,'']]],
  ['defines',['Defines',['../group___b_l_e___g_a_t_t_s___d_e_f_i_n_e_s.html',1,'']]],
  ['defines',['Defines',['../group___b_l_e___l2_c_a_p___d_e_f_i_n_e_s.html',1,'']]],
  ['dtm',['DTM',['../group__ble__sdk__app__dtm__serial.html',1,'']]],
  ['dtm_20_2d_20direct_20test_20mode',['DTM - Direct Test Mode',['../group__ble__sdk__dtmlib__dtm.html',1,'']]],
  ['device_20firmware_20update_20service',['Device Firmware Update Service',['../group__ble__sdk__srv__dfu.html',1,'']]],
  ['device_20information_20service',['Device Information Service',['../group__ble__sdk__srv__dis.html',1,'']]],
  ['data_20structures',['Data Structures',['../group___d_a_t_a___s_t_r_u_c_t_u_r_e_s.html',1,'']]],
  ['defines',['Defines',['../group___d_e_f_i_n_e_s.html',1,'']]],
  ['dfu_20profile_20specification',['DFU Profile Specification',['../group__dfu__ble__profile__spec.html',1,'']]],
  ['dfu_20service_20specification',['DFU Service Specification',['../group__dfu__ble__service__spec.html',1,'']]],
  ['dual_20bank_20flash_20layout',['Dual Bank Flash Layout',['../group__dfu__mem__layout__dual__bank.html',1,'']]],
  ['definitions',['Definitions',['../group__foftt__ant__sdm__rx__module__definitions.html',1,'']]],
  ['data_20page_202_20_2d_20status_20byte_20definitions',['Data page 2 - Status byte definitions',['../group__foftt__ant__sdm__rx__page__2__status__byte__definitions.html',1,'']]],
  ['definitions',['Definitions',['../group__foftt__ant__sdm__tx__module__definitions.html',1,'']]],
  ['data_20buffer_20indices',['Data buffer indices',['../group__foftt__sdm__rx__data__buffer__indices.html',1,'']]],
  ['data_20buffer_20indices',['Data buffer indices',['../group__foftt__sdm__tx__data__buffer__indices.html',1,'']]],
  ['data_20page_202_20_2d_20status_20byte_20definitions',['Data page 2 - status byte definitions',['../group__foftt__sdm__tx__page__2__status__byte__definitions.html',1,'']]],
  ['device_20firmware_20update_20api_2e',['Device Firmware Update API.',['../group__nrf__dfu.html',1,'']]],
  ['dfu_20transport_20api_2e',['DFU transport API.',['../group__nrf__dfu__transport.html',1,'']]],
  ['drivers',['Drivers',['../group__nrf__drivers.html',1,'']]],
  ['defines_20related_20to_20serialized_20ble_20commands_2e',['Defines related to serialized BLE commands.',['../group__rpc__cmd__defines.html',1,'']]],
  ['data_20buffer_20indices',['Data buffer indices',['../group__sdm__rx__data__buffer__indices.html',1,'']]],
  ['data_20buffer_20indices',['Data buffer indices',['../group__sdm__tx__data__buffer__indices.html',1,'']]],
  ['data_20page_202_20_2d_20status_20byte_20definitions',['Data page 2 - status byte definitions',['../group__sdm__tx__page__2__status__byte__definitions.html',1,'']]]
];
