var searchData=
[
  ['button_20handler',['Button Handler',['../group__app__button.html',1,'']]],
  ['bluetooth_20appearance_20values',['Bluetooth Appearance values',['../group___b_l_e___a_p_p_e_a_r_a_n_c_e_s.html',1,'']]],
  ['ble_20s110_20_2d_20serialization',['BLE S110 - Serialization',['../group__ble__apps__serialization.html',1,'']]],
  ['ble_20softdevice_20common',['BLE SoftDevice Common',['../group___b_l_e___c_o_m_m_o_n.html',1,'']]],
  ['ble_20connection_20handles',['BLE Connection Handles',['../group___b_l_e___c_o_n_n___h_a_n_d_l_e_s.html',1,'']]],
  ['bluetooth_20status_20codes',['Bluetooth status codes',['../group___b_l_e___h_c_i___s_t_a_t_u_s___c_o_d_e_s.html',1,'']]],
  ['blood_20pressure_20application',['Blood Pressure Application',['../group__ble__sdk__app__bps.html',1,'']]],
  ['ble_20s110_20connectivity_20chip',['BLE S110 Connectivity Chip',['../group__ble__sdk__app__connectivity.html',1,'']]],
  ['blood_20glucose_20application',['Blood Glucose Application',['../group__ble__sdk__app__gls.html',1,'']]],
  ['bluetooth_20part_20of_20multiprotocol_20application',['Bluetooth part of Multiprotocol Application',['../group__ble__sdk__app__gzll__bluetooth__part.html',1,'']]],
  ['ble_20s110',['BLE S110',['../group__ble__sdk__apps.html',1,'']]],
  ['ble_20s110',['BLE S110',['../group__ble__sdk__apps__eval.html',1,'']]],
  ['bootloader_2fdfu',['Bootloader/DFU',['../group__ble__sdk__bootloader.html',1,'']]],
  ['bluetooth_20libraries',['Bluetooth Libraries',['../group__ble__sdk__lib.html',1,'']]],
  ['bonds_20and_20persistent_20data_20manager',['Bonds and Persistent Data Manager',['../group__ble__sdk__lib__bond__manager.html',1,'']]],
  ['bluetooth_20libraries',['Bluetooth Libraries',['../group__ble__sdk__lib__serialization.html',1,'']]],
  ['bluetooth_20services',['Bluetooth Services',['../group__ble__sdk__srv.html',1,'']]],
  ['battery_20service',['Battery Service',['../group__ble__sdk__srv__bas.html',1,'']]],
  ['blood_20pressure_20service',['Blood Pressure Service',['../group__ble__sdk__srv__bps.html',1,'']]],
  ['ble_20date_20time_20characteristic_20type',['BLE Date Time characteristic type',['../group__ble__sdk__srv__date__time.html',1,'']]],
  ['ble_20stack_20event_20handler',['BLE Stack Event Handler',['../group__ble__stack__handler.html',1,'']]],
  ['button_20debouncer_20example',['Button Debouncer Example',['../group__debouncer__example.html',1,'']]],
  ['ble',['BLE',['../group__dfu__transport__ble.html',1,'']]],
  ['button_20debouncer_20example',['Button Debouncer Example',['../group__foftt__debouncer__example.html',1,'']]],
  ['blinky_20example',['Blinky Example',['../group__foftt__gpio__example.html',1,'']]],
  ['blinky_20example',['Blinky Example',['../group__gpio__example.html',1,'']]],
  ['blinky_20example',['Blinky Example',['../group__gpio__example__pca10001.html',1,'']]],
  ['blinky_20example',['Blinky Example',['../group__gpio__example__pca10003.html',1,'']]],
  ['ble_20s110_20events',['BLE S110 Events',['../group__nrf51__encoding__events__serialization.html',1,'']]],
  ['ble_20s110_20functions',['BLE S110 Functions',['../group__nrf51__encoding__functions__serialization.html',1,'']]],
  ['bootloader_20api_2e',['Bootloader API.',['../group__nrf__bootloader.html',1,'']]],
  ['bootloader_20util_20api_2e',['Bootloader util API.',['../group__nrf__bootloader__util.html',1,'']]]
];
