var searchData=
[
  ['gpiote_20handler',['GPIOTE Handler',['../group__app__gpiote.html',1,'']]],
  ['general_20error_20codes',['General error codes',['../group__ble__err.html',1,'']]],
  ['generic_20access_20profile_20_28gap_29',['Generic Access Profile (GAP)',['../group___b_l_e___g_a_p.html',1,'']]],
  ['gap_20advertising_20and_20scan_20response_20data_20format',['GAP Advertising and Scan Response Data format',['../group___b_l_e___g_a_p___a_d___t_y_p_e___d_e_f_i_n_i_t_i_o_n_s.html',1,'']]],
  ['gap_20address_20types',['GAP Address types',['../group___b_l_e___g_a_p___a_d_d_r___t_y_p_e_s.html',1,'']]],
  ['gap_20advertising_20filter_20policies',['GAP Advertising filter policies',['../group___b_l_e___g_a_p___a_d_v___f_i_l_t_e_r___p_o_l_i_c_i_e_s.html',1,'']]],
  ['gap_20advertisement_20flags',['GAP Advertisement Flags',['../group___b_l_e___g_a_p___a_d_v___f_l_a_g_s.html',1,'']]],
  ['gap_20advertising_20interval_20max_20and_20min',['GAP Advertising interval max and min',['../group___b_l_e___g_a_p___a_d_v___i_n_t_e_r_v_a_l_s.html',1,'']]],
  ['gap_20advertisement',['GAP Advertisement',['../group___b_l_e___g_a_p___a_d_v___m_s_c.html',1,'']]],
  ['gap_20advertising_20timeout_20values',['GAP Advertising timeout values',['../group___b_l_e___g_a_p___a_d_v___t_i_m_e_o_u_t___v_a_l_u_e_s.html',1,'']]],
  ['gap_20advertising_20types',['GAP Advertising types',['../group___b_l_e___g_a_p___a_d_v___t_y_p_e_s.html',1,'']]],
  ['gap_20authentication_20key_20types',['GAP Authentication Key Types',['../group___b_l_e___g_a_p___a_u_t_h___k_e_y___t_y_p_e_s.html',1,'']]],
  ['gap_20bonding_3a_20just_20works',['GAP Bonding: Just Works',['../group___b_l_e___g_a_p___b_o_n_d_i_n_g___j_w___m_s_c.html',1,'']]],
  ['gap_20bonding_3a_20passkey_20entry_20_28central_20display_29_20or_20oob_20msc',['GAP Bonding: Passkey Entry (Central display) or OOB MSC',['../group___b_l_e___g_a_p___b_o_n_d_i_n_g___p_k___c_e_n_t_r_a_l___o_o_b___m_s_c.html',1,'']]],
  ['gap_20bonding_3a_20passkey_20entry_2c_20peripheral_20displays',['GAP Bonding: Passkey Entry, Peripheral displays',['../group___b_l_e___g_a_p___b_o_n_d_i_n_g___p_k___p_e_r_i_p_h___m_s_c.html',1,'']]],
  ['gap_20connection_20establishment_20and_20termination',['GAP Connection Establishment and Termination',['../group___b_l_e___g_a_p___c_o_n_n___m_s_c.html',1,'']]],
  ['gap_20attribute_20security_20requirement_20setters',['GAP attribute security requirement setters',['../group___b_l_e___g_a_p___c_o_n_n___s_e_c___m_o_d_e___s_e_t___m_a_c_r_o_s.html',1,'']]],
  ['gap_20connection_20parameters_20limits',['GAP Connection Parameters Limits',['../group___b_l_e___g_a_p___c_p___l_i_m_i_t_s.html',1,'']]],
  ['gap_20connection_20parameter_20update',['GAP Connection Parameter Update',['../group___b_l_e___g_a_p___c_p_u___m_s_c.html',1,'']]],
  ['gap_20discovery_20modes',['GAP Discovery modes',['../group___b_l_e___g_a_p___d_i_s_c___m_o_d_e_s.html',1,'']]],
  ['gap_20io_20capabilities',['GAP IO Capabilities',['../group___b_l_e___g_a_p___i_o___c_a_p_s.html',1,'']]],
  ['gap_20pairing_3a_20just_20works',['GAP Pairing: Just Works',['../group___b_l_e___g_a_p___p_a_i_r_i_n_g___j_w___m_s_c.html',1,'']]],
  ['gap_20peripheral_20initiated_20security_20establishment',['GAP Peripheral Initiated Security Establishment',['../group___b_l_e___g_a_p___p_e_r_i_p_h___s_e_c___m_s_c.html',1,'']]],
  ['gap_20roles',['GAP Roles',['../group___b_l_e___g_a_p___r_o_l_e_s.html',1,'']]],
  ['gap_20rssi',['GAP RSSI',['../group___b_l_e___g_a_p___r_s_s_i___m_s_c.html',1,'']]],
  ['gap_20security_20establishment_20using_20stored_20keys',['GAP Security Establishment using stored keys',['../group___b_l_e___g_a_p___s_e_c___m_s_c.html',1,'']]],
  ['gap_20security_20status',['GAP Security status',['../group___b_l_e___g_a_p___s_e_c___s_t_a_t_u_s.html',1,'']]],
  ['gap_20security_20status_20sources',['GAP Security status sources',['../group___b_l_e___g_a_p___s_e_c___s_t_a_t_u_s___s_o_u_r_c_e_s.html',1,'']]],
  ['gap_20timeout_20sources',['GAP Timeout sources',['../group___b_l_e___g_a_p___t_i_m_e_o_u_t___s_o_u_r_c_e_s.html',1,'']]],
  ['generic_20attribute_20profile_20_28gatt_29_20common',['Generic Attribute Profile (GATT) Common',['../group___b_l_e___g_a_t_t.html',1,'']]],
  ['gatt_20bluetooth_20namespaces',['GATT Bluetooth Namespaces',['../group___b_l_e___g_a_t_t___c_p_f___n_a_m_e_s_p_a_c_e_s.html',1,'']]],
  ['gatt_20handle_20value_20operations',['GATT Handle Value operations',['../group___b_l_e___g_a_t_t___h_v_x___t_y_p_e_s.html',1,'']]],
  ['gatt_20status_20codes',['GATT Status Codes',['../group___b_l_e___g_a_t_t___s_t_a_t_u_s___c_o_d_e_s.html',1,'']]],
  ['gatt_20timeout_20sources',['GATT Timeout sources',['../group___b_l_e___g_a_t_t___t_i_m_e_o_u_t___s_o_u_r_c_e_s.html',1,'']]],
  ['gatt_20write_20operations',['GATT Write operations',['../group___b_l_e___g_a_t_t___w_r_i_t_e___o_p_s.html',1,'']]],
  ['generic_20attribute_20profile_20_28gatt_29_20client',['Generic Attribute Profile (GATT) Client',['../group___b_l_e___g_a_t_t_c.html',1,'']]],
  ['gattc_20characteristic_20discovery',['GATTC Characteristic Discovery',['../group___b_l_e___g_a_t_t_c___c_h_a_r___d_i_s_c___m_s_c.html',1,'']]],
  ['gattc_20descriptor_20discovery',['GATTC Descriptor Discovery',['../group___b_l_e___g_a_t_t_c___d_e_s_c___d_i_s_c___m_s_c.html',1,'']]],
  ['gattc_20handle_20value_20indication',['GATTC Handle Value Indication',['../group___b_l_e___g_a_t_t_c___h_v_i___m_s_c.html',1,'']]],
  ['gattc_20handle_20value_20notification',['GATTC Handle Value Notification',['../group___b_l_e___g_a_t_t_c___h_v_n___m_s_c.html',1,'']]],
  ['gattc_20primary_20service_20discovery',['GATTC Primary Service Discovery',['../group___b_l_e___g_a_t_t_c___p_r_i_m___s_r_v_c___d_i_s_c___m_s_c.html',1,'']]],
  ['gattc_20read_20multiple_20characteristic_20values',['GATTC Read Multiple Characteristic Values',['../group___b_l_e___g_a_t_t_c___r_e_a_d___m_u_l_t___m_s_c.html',1,'']]],
  ['gattc_20read_20characteristic_20value_20by_20uuid',['GATTC Read Characteristic Value by UUID',['../group___b_l_e___g_a_t_t_c___r_e_a_d___u_u_i_d___m_s_c.html',1,'']]],
  ['gattc_20relationship_20discovery',['GATTC Relationship Discovery',['../group___b_l_e___g_a_t_t_c___r_e_l___d_i_s_c___m_s_c.html',1,'']]],
  ['gattc_20timeout',['GATTC Timeout',['../group___b_l_e___g_a_t_t_c___t_i_m_e_o_u_t___m_s_c.html',1,'']]],
  ['gattc_20characteristic_20or_20descriptor_20value_20read',['GATTC Characteristic or Descriptor Value Read',['../group___b_l_e___g_a_t_t_c___v_a_l_u_e___r_e_a_d___m_s_c.html',1,'']]],
  ['gattc_20characteristic_20or_20descriptor_20value_20write',['GATTC Characteristic or Descriptor Value Write',['../group___b_l_e___g_a_t_t_c___v_a_l_u_e___w_r_i_t_e___m_s_c.html',1,'']]],
  ['generic_20attribute_20profile_20_28gatt_29_20server',['Generic Attribute Profile (GATT) Server',['../group___b_l_e___g_a_t_t_s.html',1,'']]],
  ['gatts_20att_20table_20population',['GATTS ATT Table Population',['../group___b_l_e___g_a_t_t_s___a_t_t___t_a_b_l_e___p_o_p___m_s_c.html',1,'']]],
  ['gatt_20server_20attribute_20types',['GATT Server Attribute Types',['../group___b_l_e___g_a_t_t_s___a_t_t_r___t_y_p_e_s.html',1,'']]],
  ['gatt_20server_20authorization_20types',['GATT Server Authorization Types',['../group___b_l_e___g_a_t_t_s___a_u_t_h_o_r_i_z_e___t_y_p_e_s.html',1,'']]],
  ['gatts_20handle_20value_20indication',['GATTS Handle Value Indication',['../group___b_l_e___g_a_t_t_s___h_v_i___m_s_c.html',1,'']]],
  ['gatts_20handle_20value_20notification',['GATTS Handle Value Notification',['../group___b_l_e___g_a_t_t_s___h_v_n___m_s_c.html',1,'']]],
  ['gatts_20handle_20value_20indication_20or_20notification_20disabled',['GATTS Handle Value Indication or Notification disabled',['../group___b_l_e___g_a_t_t_s___h_v_x___d_i_s_a_b_l_e_d___m_s_c.html',1,'']]],
  ['gatts_20handle_20value_20indication_20or_20notification_20with_20system_20attributes_20missing',['GATTS Handle Value Indication or Notification with System Attributes Missing',['../group___b_l_e___g_a_t_t_s___h_v_x___s_y_s___a_t_t_r_s___m_i_s_s_i_n_g___m_s_c.html',1,'']]],
  ['gatt_20server_20operations',['GATT Server Operations',['../group___b_l_e___g_a_t_t_s___o_p_s.html',1,'']]],
  ['gatts_20read_20request_20with_20authorization',['GATTS Read Request with Authorization',['../group___b_l_e___g_a_t_t_s___r_e_a_d___r_e_q___a_u_t_h___m_s_c.html',1,'']]],
  ['gatts_20service_20changed',['GATTS Service Changed',['../group___b_l_e___g_a_t_t_s___s_c___m_s_c.html',1,'']]],
  ['gatt_20server_20service_20types',['GATT Server Service Types',['../group___b_l_e___g_a_t_t_s___s_r_v_c___t_y_p_e_s.html',1,'']]],
  ['gatts_20system_20attributes_20handling_3a_20bonded_20peer',['GATTS System Attributes Handling: Bonded Peer',['../group___b_l_e___g_a_t_t_s___s_y_s___a_t_t_r_s___b_o_n_d_e_d___p_e_e_r___m_s_c.html',1,'']]],
  ['gatts_20system_20attributes_20handling_3a_20unknown_20peer',['GATTS System Attributes Handling: Unknown Peer',['../group___b_l_e___g_a_t_t_s___s_y_s___a_t_t_r_s___u_n_k___p_e_e_r___m_s_c.html',1,'']]],
  ['gatt_20value_20locations',['GATT Value Locations',['../group___b_l_e___g_a_t_t_s___v_l_o_c_s.html',1,'']]],
  ['gatts_20write_20command_20with_20or_20without_20authorization',['GATTS Write Command with or without Authorization',['../group___b_l_e___g_a_t_t_s___w_r_i_t_e___c_m_d___n_o___a_u_t_h___m_s_c.html',1,'']]],
  ['gatts_20write_20request_20with_20authorization',['GATTS Write Request with Authorization',['../group___b_l_e___g_a_t_t_s___w_r_i_t_e___r_e_q___a_u_t_h___m_s_c.html',1,'']]],
  ['gatts_20write_20request_20without_20authorization',['GATTS Write Request without Authorization',['../group___b_l_e___g_a_t_t_s___w_r_i_t_e___r_e_q___n_o___a_u_t_h___m_s_c.html',1,'']]],
  ['gap_20command_20decoder',['GAP Command Decoder',['../group__ble__rpc__cmd__decoder__gap.html',1,'']]],
  ['gatts_20command_20decoder',['GATTS Command Decoder',['../group__ble__rpc__cmd__decoder__gatts.html',1,'']]],
  ['gap_20event_20encoder',['GAP Event Encoder',['../group__ble__rpc__event__encoder__gap.html',1,'']]],
  ['gatts_20events_20encoder',['GATTS Events Encoder',['../group__ble__rpc__event__encoder__gatts.html',1,'']]],
  ['gap_20event_20decoder',['GAP Event Decoder',['../group__ble__rpc__evt__decoder__gap.html',1,'']]],
  ['gatts_20event_20decoder',['GATTS Event Decoder',['../group__ble__rpc__evt__decoder__gatts.html',1,'']]],
  ['gazell_20part_20of_20multiprotocol_20application',['Gazell part of Multiprotocol Application',['../group__ble__sdk__app__gzll__gazell__part.html',1,'']]],
  ['glucose_20service',['Glucose Service',['../group__ble__sdk__srv__gls.html',1,'']]],
  ['glucose_20database_20service',['Glucose Database Service',['../group__ble__sdk__srv__gls__db.html',1,'']]],
  ['gpiote_20example',['GPIOTE Example',['../group__foftt__nrf__gpiote__example.html',1,'']]],
  ['gpio_20log_20settings',['GPIO log settings',['../group__foftt__sdm__rx__gpio__log__settings.html',1,'']]],
  ['gpio_20log_20settings',['GPIO log settings',['../group__foftt__sdm__tx__gpio__log__settings.html',1,'']]],
  ['gap_20security_20modes',['GAP Security Modes',['../group___g_a_p___s_e_c___m_o_d_e_s.html',1,'']]],
  ['gazell_20link_20layer_20user_20guide',['Gazell Link Layer User Guide',['../group__gzll__02__user__guide.html',1,'']]],
  ['gazell_20link_20layer',['Gazell Link Layer',['../group__gzll__03__examples.html',1,'']]],
  ['gazell_20link_20layer_20device_20with_20payload_20in_20ack',['Gazell Link Layer Device with Payload in ACK',['../group__gzll__device__ack__payload__example.html',1,'']]],
  ['gazell_20link_20layer_20host_20with_20payload_20in_20ack',['Gazell Link Layer Host with Payload in ACK',['../group__gzll__host__ack__payload__example.html',1,'']]],
  ['gazell_20pairing_20user_20guide',['Gazell Pairing User Guide',['../group__gzp__02__user__guide.html',1,'']]],
  ['gazell_20pairing',['Gazell Pairing',['../group__gzp__03__examples.html',1,'']]],
  ['gazell_20pairing_20desktop_20device_20emulator',['Gazell Pairing Desktop Device Emulator',['../group__gzp__desktop__device__emulator__example.html',1,'']]],
  ['gazell_20pairing_20device_20with_20dynamic_20pairing',['Gazell Pairing Device with Dynamic Pairing',['../group__gzp__device__dynamic__pairing__example.html',1,'']]],
  ['gazell_20pairing_20host_20with_20dynamic_20pairing',['Gazell Pairing Host with Dynamic Pairing',['../group__gzp__host__dynamic__pairing__example.html',1,'']]],
  ['gazell_20pairing_20common_20functions_20implementation',['Gazell Pairing common functions implementation',['../group__gzp__source__common.html',1,'']]],
  ['gazell_20pairing_20device_20implementation_2e',['Gazell Pairing Device implementation.',['../group__gzp__source__device.html',1,'']]],
  ['gazell_20pairing_20host_20implementation',['Gazell Pairing Host implementation',['../group__gzp__source__host.html',1,'']]],
  ['gazell_20pairing_20host_20nrf51_20specific_20implementation',['Gazell Pairing Host nRF51 specific implementation',['../group__gzp__source__host__nrf51.html',1,'']]],
  ['gazell_20link_20layer',['Gazell Link Layer',['../group__modules__01__gzll.html',1,'']]],
  ['gazell_20pairing',['Gazell Pairing',['../group__modules__02__gzp.html',1,'']]],
  ['gzll',['GZLL',['../group__nrf518__examples__nrf6310__gzll.html',1,'']]],
  ['gzll',['GZLL',['../group__nrf518__examples__pca10000__gzll.html',1,'']]],
  ['gzll',['GZLL',['../group__nrf518__examples__pca10001__gzll.html',1,'']]],
  ['gazell',['Gazell',['../group__nrf518__lib__gazell.html',1,'']]],
  ['gpio_20abstraction',['GPIO abstraction',['../group__nrf__gpio.html',1,'']]],
  ['gpiote_20abstraction',['GPIOTE abstraction',['../group__nrf__gpiote.html',1,'']]],
  ['gpiote_20example',['GPIOTE Example',['../group__nrf__gpiote__example.html',1,'']]],
  ['gpio_20log_20settings',['GPIO log settings',['../group__sdm__rx__gpio__log__settings.html',1,'']]],
  ['gpio_20log_20settings',['GPIO log settings',['../group__sdm__tx__gpio__log__settings.html',1,'']]]
];
