var searchData=
[
  ['sdm_20tx_20module_20error_20codes',['SDM TX module error codes',['../group__ant__sdm__tx__module__error__codes.html',1,'']]],
  ['sdm_20data_20update_20timer',['SDM data update timer',['../group__ant__sdm__tx__timer.html',1,'']]],
  ['scheduler',['Scheduler',['../group__app__scheduler.html',1,'']]],
  ['svc_20return_20values_20specific_20to_20gap',['SVC return values specific to GAP',['../group___b_l_e___e_r_r_o_r_s___g_a_p.html',1,'']]],
  ['svc_20return_20values_20specific_20to_20gattc',['SVC return values specific to GATTC',['../group___b_l_e___e_r_r_o_r_s___g_a_t_t_c.html',1,'']]],
  ['svc_20return_20values_20specific_20to_20gatts',['SVC return values specific to GATTS',['../group___b_l_e___e_r_r_o_r_s___g_a_t_t_s.html',1,'']]],
  ['svc_20return_20values_20specific_20to_20l2cap',['SVC return values specific to L2CAP',['../group___b_l_e___e_r_r_o_r_s___l2_c_a_p.html',1,'']]],
  ['structures',['Structures',['../group___b_l_e___g_a_p___s_t_r_u_c_t_u_r_e_s.html',1,'']]],
  ['structures',['Structures',['../group___b_l_e___g_a_t_t___s_t_r_u_c_t_u_r_e_s.html',1,'']]],
  ['structures',['Structures',['../group___b_l_e___g_a_t_t_c___s_t_r_u_c_t_u_r_e_s.html',1,'']]],
  ['structures',['Structures',['../group___b_l_e___g_a_t_t_s___s_t_r_u_c_t_u_r_e_s.html',1,'']]],
  ['structures',['Structures',['../group___b_l_e___l2_c_a_p___s_t_r_u_c_t_u_r_e_s.html',1,'']]],
  ['sensor_20data_20simulator',['Sensor Data Simulator',['../group__ble__sdk__lib__sensorsim.html',1,'']]],
  ['speed_20and_20cadence_20control_20point',['Speed and Cadence Control Point',['../group__ble__sdk__srv__sc__ctrlpt.html',1,'']]],
  ['single_20bank_20flash_20layout',['Single Bank Flash Layout',['../group__dfu__mem__layout__single__bank.html',1,'']]],
  ['serial_20_28hci_29',['Serial (HCI)',['../group__dfu__transport__serial.html',1,'']]],
  ['sdm_20tx_20module_20error_20codes',['SDM TX module error codes',['../group__foftt__ant__sdm__tx__module__error__codes.html',1,'']]],
  ['sdm_20data_20update_20timer',['SDM data update timer',['../group__foftt__ant__sdm__tx__timer.html',1,'']]],
  ['softdevice_20global_20error_20codes',['SoftDevice Global Error Codes',['../group__foftt__nrf__error.html',1,'']]],
  ['softdevice_20manager_20api',['SoftDevice Manager API',['../group__foftt__nrf__sdm__api.html',1,'']]],
  ['softdevice_20manager_20error_20codes',['SoftDevice Manager Error Codes',['../group__foftt__nrf__sdm__error.html',1,'']]],
  ['soc_20library_20api',['SoC Library API',['../group__foftt__nrf__soc__api.html',1,'']]],
  ['soc_20library_20error_20codes',['SoC Library Error Codes',['../group__foftt__nrf__soc__error.html',1,'']]],
  ['spi_20master_20loopback_20example',['SPI master Loopback Example',['../group__foftt__spi__master__example.html',1,'']]],
  ['source',['Source',['../group__gzp__04__source.html',1,'']]],
  ['slip_20module',['SLIP module',['../group__hci__slip.html',1,'']]],
  ['software_20controlled_20spi_20master_20driver',['Software controlled SPI Master driver',['../group__lib__driver__spi__master.html',1,'']]],
  ['software_20controlled_20twi_20master_20driver',['Software controlled TWI Master driver',['../group__lib__driver__twi__master.html',1,'']]],
  ['s110_20softdevice',['S110 SoftDevice',['../group__nrf518__lib__ble__s110.html',1,'']]],
  ['setups',['Setups',['../group__nrf51__setups.html',1,'']]],
  ['simple_20uart_20driver',['Simple UART driver',['../group__nrf__drivers__simple__uart.html',1,'']]],
  ['softdevice_20global_20error_20codes',['SoftDevice Global Error Codes',['../group__nrf__error.html',1,'']]],
  ['softdevice_20manager_20api',['SoftDevice Manager API',['../group__nrf__sdm__api.html',1,'']]],
  ['softdevice_20manager_20error_20codes',['SoftDevice Manager Error Codes',['../group__nrf__sdm__error.html',1,'']]],
  ['soc_20library_20api',['SoC Library API',['../group__nrf__soc__api.html',1,'']]],
  ['soc_20library_20error_20codes',['SoC Library Error Codes',['../group__nrf__soc__error.html',1,'']]],
  ['s210_20softdevice',['S210 Softdevice',['../group___s210.html',1,'']]],
  ['spi_20master_20loopback_20example',['SPI master Loopback Example',['../group__spi__master__example.html',1,'']]],
  ['service_20uuid_20definitions',['Service UUID definitions',['../group___u_u_i_d___s_e_r_v_i_c_e_s.html',1,'']]]
];
